blueprint:

  name: ZHA - Tuya - TS004F 4 Button Remote Switch - Custom Actions

  description: >-
    This automation adds triggers for all actions of the Tuya TS004F 4 button
    remote in switch mode.

    Sold on AliExpress by brands like Moes, Girier etc.

  domain: automation

  input:
    mode:
      name: Automation Mode
      description: "https://www.home-assistant.io/docs/automation/modes/"
      default: restart
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
    max:
      name: Automation Max Queue
      description: The maximum number of runs that can be executing and/or queued up at a time.
      default: 10
      selector:
        number:
          mode: box
          min: 1
          max: 100
    remote:
      name: Tuya - TS004F 4 Button Remote
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_xabckq1v
          model: TS004F
    btn1_single:
      name: Button 1 - Top Left - Single
      selector:
        action:
      default: []
    btn1_double:
      name: Button 1 - Top Left - Double
      selector:
        action:
      default: []
    btn1_hold:
      name: Button 1 - Top Left - Hold
      selector:
        action:
      default: []
    btn2_single:
      name: Button 2 - Top Right - Single
      selector:
        action:
      default: []
    btn2_double:
      name: Button 2 - Top Right - Double
      selector:
        action:
      default: []
    btn2_hold:
      name: Button 2 - Top Right - Hold
      selector:
        action:
      default: []
    btn3_single:
      name: Button 3 - Bottom Left - Single
      selector:
        action:
      default: []
    btn3_double:
      name: Button 3 - Bottom Left - Double
      selector:
        action:
      default: []
    btn3_hold:
      name: Button 3 - Bottom Left - Hold
      selector:
        action:
      default: []
    btn4_single:
      name: Button 4 - Bottom Right - Single
      selector:
        action:
      default: []
    btn4_double:
      name: Button 4 - Bottom Right - Double
      selector:
        action:
      default: []
    btn4_hold:
      name: Button 4 - Bottom Right - Hold
      selector:
        action:
      default: []

mode: !input mode
max: !input max
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"

  - choose:

      # Button 1 - Single
      - conditions:
          - "{{ endpoint_id == 1 }}"
          - "{{ command == 'remote_button_short_press' }}"
        sequence: !input btn1_single
      # Button 1 - Double
      - conditions:
          - "{{ endpoint_id == 1 }}"
          - "{{ command == 'remote_button_double_press' }}"
        sequence: !input btn1_double
      # Button 1 - Hold
      - conditions:
          - "{{ endpoint_id == 1 }}"
          - "{{ command == 'remote_button_long_press' }}"
        sequence: !input btn1_hold

      # Button 2 - Single
      - conditions:
          - "{{ endpoint_id == 2 }}"
          - "{{ command == 'remote_button_short_press' }}"
        sequence: !input btn2_single
      # Button 2 - Double
      - conditions:
          - "{{ endpoint_id == 2 }}"
          - "{{ command == 'remote_button_double_press' }}"
        sequence: !input btn2_double
      # Button 2 - Hold
      - conditions:
          - "{{ endpoint_id == 2 }}"
          - "{{ command == 'remote_button_long_press' }}"
        sequence: !input btn2_hold

      # Button 3 - Single
      - conditions:
          - "{{ endpoint_id == 3 }}"
          - "{{ command == 'remote_button_short_press' }}"
        sequence: !input btn3_single
      # Button 3 - Double
      - conditions:
          - "{{ endpoint_id == 3 }}"
          - "{{ command == 'remote_button_double_press' }}"
        sequence: !input btn3_double
      # Button 3 - Hold
      - conditions:
          - "{{ endpoint_id == 3 }}"
          - "{{ command == 'remote_button_long_press' }}"
        sequence: !input btn3_hold

      # Button 4 - Single
      - conditions:
          - "{{ endpoint_id == 4 }}"
          - "{{ command == 'remote_button_short_press' }}"
        sequence: !input btn4_single
      # Button 4 - Double
      - conditions:
          - "{{ endpoint_id == 4 }}"
          - "{{ command == 'remote_button_double_press' }}"
        sequence: !input btn4_double
      # Button 4 - Hold
      - conditions:
          - "{{ endpoint_id == 4 }}"
          - "{{ command == 'remote_button_long_press' }}"
        sequence: !input btn4_hold

    # Any other event will cancel the repeat loops.
    default: []
